// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaRe_up;

#nullable disable

namespace PizzaReup.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20230209032607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaRe_up.Pizza", b =>
                {
                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Sauces")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ingredients");

                    b.ToTable("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
